import { Agent, Gemini, PreloadMemoryTool, FunctionTool, CallbackContext } from '@google/adk';
import { GoogleGenAI } from '@google/genai';
import { Storage } from '@google-cloud/storage';
import { GoogleAuth } from 'google-auth-library';

export const MEMORY_BANK_ID = "5621628680225685504";
export const PROJECT_ID = process.env.GOOGLE_CLOUD_PROJECT || "qwiklabs-gcp-04-a63326fe2771";
export const LOCATION = process.env.GOOGLE_CLOUD_LOCATION || "us-central1";
export const BUCKET_NAME = "apha-agent-public-images-qwiklabs-gcp-04-a63326fe2771";
export const RAG_CORPUS_NAME = `projects/${PROJECT_ID}/locations/us-central1/ragCorpora/6615444804979392512`;

const storage = new Storage({ projectId: PROJECT_ID });
const auth = new GoogleAuth({
  scopes: 'https://www.googleapis.com/auth/cloud-platform',
});

async function ensurePublicBucket(bucketName: string) {
  const bucket = storage.bucket(bucketName);
  const [exists] = await bucket.exists();
  if (!exists) {
    await storage.createBucket(bucketName, {
      location: 'us-central1',
      storageClass: 'STANDARD',
    });
  }
  return bucket;
}

// 1. RAG Knowledge Base Query Tool
export async function searchPranicKnowledgeBase(params: { query: string }) {
  try {
    const client = await auth.getClient();
    const token = await client.getAccessToken();
    const url = `https://us-central1-aiplatform.googleapis.com/v1/projects/${PROJECT_ID}/locations/us-central1:retrieveContexts`;

    const res = await fetch(url, {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${token.token}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        vertexRagStore: {
          ragResources: [{ ragCorpus: RAG_CORPUS_NAME }]
        },
        query: { text: params.query || 'Pranic Healing basics' }
      })
    });

    const data = await res.json();
    const contexts = data?.contexts?.contexts || [];

    if (!contexts.length) {
      return "No specific details found in the Pranic Healing RAG knowledge base for that query.";
    }

    const passages = contexts.map((c: any) => c.text).filter(Boolean);
    const textResult = passages.join("\n\n---\n\n");

    return {
      passages: textResult,
      source: "pranic-healing-guide-corpus",
      a2uiSurface: {
        type: "Card",
        header: `Pranic Healing RAG Knowledge: ${params.query}`,
        fields: [
          { label: "Corpus Source", value: "pranic-healing-guide-corpus" },
          { label: "Excerpts Retrieved", value: `${passages.length} passages` }
        ]
      }
    };
  } catch (err: any) {
    console.error('RAG Retrieval Error:', err);
    return `Error querying RAG knowledge base: ${err.message || err}`;
  }
}

// 2. Image Generation Tool using gemini-3.1-flash-lite-image in global region
export async function generateDomainImage(
  params: { prompt?: string; itemName?: string },
  toolContext?: any
) {
  const ai = new GoogleGenAI({
    vertexai: true,
    project: PROJECT_ID,
    location: 'global',
  });

  const fullPrompt = `Generate a high quality visual graphic for American Pranic Healing Association (APHA): ${params.prompt || params.itemName || 'Meditation on Twin Hearts lotus banner'}`;

  const response = await ai.models.generateContent({
    model: 'gemini-3.1-flash-lite-image',
    contents: fullPrompt,
  });

  const part = response.candidates?.[0]?.content?.parts?.[0];
  if (!part || !part.inlineData || !part.inlineData.data) {
    throw new Error('No image generated by gemini-3.1-flash-lite-image');
  }

  const mimeType = part.inlineData.mimeType || 'image/png';
  const base64Data = part.inlineData.data;
  const imageBuffer = Buffer.from(base64Data, 'base64');

  const timestamp = Date.now();
  const itemNameSlug = (params.itemName || 'apha-visual')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-');
  const filename = `${itemNameSlug}-${timestamp}.${mimeType.includes('jpeg') || mimeType.includes('jpg') ? 'jpg' : 'png'}`;

  // Save artifact for Playground Artifacts panel
  if (toolContext && typeof toolContext.saveArtifact === 'function') {
    try {
      await toolContext.saveArtifact(filename, {
        inlineData: {
          mimeType,
          data: base64Data,
        },
      });
      console.log(`Saved artifact "${filename}" via toolContext.saveArtifact.`);
    } catch (err) {
      console.warn('saveArtifact note:', err);
    }
  }

  // Upload image bytes to Cloud Storage bucket and return public HTTPS URL
  const bucket = await ensurePublicBucket(BUCKET_NAME);
  const file = bucket.file(filename);

  await file.save(imageBuffer, {
    metadata: { contentType: mimeType },
    public: true,
    resumable: false,
  });

  try {
    await file.makePublic();
  } catch (e) {
    // Ignore error if uniform bucket-level access is enabled
  }

  const publicUrl = `https://storage.googleapis.com/${BUCKET_NAME}/${filename}`;

  return {
    success: true,
    filename,
    mimeType,
    publicUrl,
    a2uiSurface: {
      type: "Card",
      header: `APHA Visual: ${params.itemName || 'Pranic Healing Graphic'}`,
      fields: [
        { label: "Public Storage URL", value: publicUrl },
        { label: "Mime Type", value: mimeType }
      ],
      image: { url: publicUrl }
    }
  };
}

// 3. Memory generation callback
export async function generateMemoriesCallback(ctx: CallbackContext) {
  if (ctx.addSessionToMemory) {
    await ctx.addSessionToMemory();
  }
}

// 4. APHA Domain Tools
export function getUpcomingEvents(params: { level?: string; location?: string }) {
  const events = [
    {
      title: "Basic Pranic Healing (Level 1)",
      level: "Basic",
      dates: "Aug 15-16, 2026",
      location: "Los Angeles, CA & Online",
      instructor: "Dr. Mary Clark",
      prerequisites: "None",
      registrationUrl: "https://pranichealing.us/events/basic-la",
      a2uiSurface: {
        type: "Card",
        header: "Basic Pranic Healing (Level 1)",
        fields: [
          { label: "Dates", value: "Aug 15-16, 2026" },
          { label: "Location", value: "Los Angeles, CA & Online" },
          { label: "Instructor", value: "Dr. Mary Clark" },
          { label: "Prerequisites", value: "None" }
        ],
        action: { label: "Register at pranichealing.us", url: "https://pranichealing.us/events/basic-la" }
      }
    },
    {
      title: "Advanced Pranic Healing (Level 2)",
      level: "Advanced",
      dates: "Aug 22-23, 2026",
      location: "Los Angeles, CA",
      instructor: "Master Stephen Co",
      prerequisites: "Basic Pranic Healing",
      registrationUrl: "https://pranichealing.us/events/advanced-la",
      a2uiSurface: {
        type: "Card",
        header: "Advanced Pranic Healing (Level 2)",
        fields: [
          { label: "Dates", value: "Aug 22-23, 2026" },
          { label: "Location", value: "Los Angeles, CA" },
          { label: "Instructor", value: "Master Stephen Co" },
          { label: "Prerequisites", value: "Basic Pranic Healing" }
        ],
        action: { label: "Register at pranichealing.us", url: "https://pranichealing.us/events/advanced-la" }
      }
    },
    {
      title: "Pranic Psychotherapy (Level 3)",
      level: "Psychotherapy",
      dates: "Sep 12-13, 2026",
      location: "Online / Zoom",
      instructor: "Master Stephen Co",
      prerequisites: "Advanced Pranic Healing",
      registrationUrl: "https://pranichealing.us/events/psychotherapy",
      a2uiSurface: {
        type: "Card",
        header: "Pranic Psychotherapy (Level 3)",
        fields: [
          { label: "Dates", value: "Sep 12-13, 2026" },
          { label: "Location", value: "Online / Zoom" },
          { label: "Instructor", value: "Master Stephen Co" },
          { label: "Prerequisites", value: "Advanced Pranic Healing" }
        ],
        action: { label: "Register at pranichealing.us", url: "https://pranichealing.us/events/psychotherapy" }
      }
    },
    {
      title: "Full Moon Planetary Meditation for Peace",
      level: "All",
      dates: "Aug 28, 2026",
      location: "Global Online",
      instructor: "APHA Instructors",
      prerequisites: "None",
      registrationUrl: "https://pranichealing.us/events/full-moon",
      a2uiSurface: {
        type: "Card",
        header: "Full Moon Planetary Meditation for Peace",
        fields: [
          { label: "Dates", value: "Aug 28, 2026" },
          { label: "Location", value: "Global Online" },
          { label: "Instructor", value: "APHA Instructors" },
          { label: "Prerequisites", value: "None" }
        ],
        action: { label: "Join Meditation", url: "https://pranichealing.us/events/full-moon" }
      }
    }
  ];

  if (!params.level && !params.location) return events;

  return events.filter(e => {
    const matchLevel = !params.level || e.level.toLowerCase().includes(params.level.toLowerCase());
    const matchLoc = !params.location || e.location.toLowerCase().includes(params.location.toLowerCase());
    return matchLevel && matchLoc;
  });
}

export function findStudyGroups(params: { cityOrZip?: string }) {
  const groups = [
    {
      name: "Los Angeles Pranic Healing Center",
      city: "Los Angeles",
      address: "123 Healing Way, Los Angeles, CA",
      meditationSchedule: "Wednesdays 7:00 PM (Twin Hearts Meditation)",
      contact: "la@pranichealing.us",
      a2uiSurface: {
        type: "Card",
        header: "Los Angeles Pranic Healing Center",
        fields: [
          { label: "City", value: "Los Angeles" },
          { label: "Address", value: "123 Healing Way, Los Angeles, CA" },
          { label: "Meditation Schedule", value: "Wednesdays 7:00 PM (Twin Hearts Meditation)" },
          { label: "Contact", value: "la@pranichealing.us" }
        ]
      }
    },
    {
      name: "Southern California Practice Circle",
      city: "Irvine",
      address: "456 Energy Blvd, Irvine, CA",
      meditationSchedule: "Saturdays 10:00 AM",
      contact: "oc@pranichealing.us",
      a2uiSurface: {
        type: "Card",
        header: "Southern California Practice Circle",
        fields: [
          { label: "City", value: "Irvine" },
          { label: "Address", value: "456 Energy Blvd, Irvine, CA" },
          { label: "Meditation Schedule", value: "Saturdays 10:00 AM" },
          { label: "Contact", value: "oc@pranichealing.us" }
        ]
      }
    },
    {
      name: "Online Global Meditation Group",
      city: "Online",
      address: "Zoom",
      meditationSchedule: "Daily 6:00 PM PST",
      contact: "online@pranichealing.us",
      a2uiSurface: {
        type: "Card",
        header: "Online Global Meditation Group",
        fields: [
          { label: "City", value: "Online / Zoom" },
          { label: "Schedule", value: "Daily 6:00 PM PST" },
          { label: "Contact", value: "online@pranichealing.us" }
        ]
      }
    }
  ];

  if (!params.cityOrZip) return groups;
  return groups.filter(g => 
    g.city.toLowerCase().includes(params.cityOrZip!.toLowerCase()) || 
    g.name.toLowerCase().includes(params.cityOrZip!.toLowerCase())
  );
}

export async function getPranicFaq(params: { topic?: string }) {
  if (params.topic) {
    return await searchPranicKnowledgeBase({ query: params.topic });
  }
  return await searchPranicKnowledgeBase({ query: "Pranic Healing core principles and FAQ" });
}

export function calculateBundleFee(params: { numWorkshops: number; isEarlyBird?: boolean }) {
  const baseRate = 350;
  const total = params.numWorkshops * baseRate;
  let discount = 0;

  if (params.numWorkshops >= 2) discount += 0.15;
  if (params.isEarlyBird) discount += 0.10;

  const finalTotal = total * (1 - discount);
  return {
    numWorkshops: params.numWorkshops,
    baseTotal: total,
    discountPercent: `${Math.round(discount * 100)}%`,
    finalTotal: `$${finalTotal.toFixed(2)}`,
    a2uiSurface: {
      type: "Card",
      header: "Workshop Package Pricing Summary",
      fields: [
        { label: "Number of Workshops", value: String(params.numWorkshops) },
        { label: "Base Total", value: `$${total.toFixed(2)}` },
        { label: "Applied Discount", value: `${Math.round(discount * 100)}%` },
        { label: "Final Total", value: `$${finalTotal.toFixed(2)}` }
      ]
    }
  };
}

const apiKey = process.env.GOOGLE_GENAI_API_KEY || process.env.GEMINI_API_KEY || 'adc_placeholder';

// 5. Root Agent Definition
export const rootAgent = new Agent({
  name: "apha_learning_assistant",
  model: new Gemini({
    model: "gemini-2.5-flash",
    apiKey,
    project: PROJECT_ID,
    location: LOCATION,
    vertexai: true,
  }),
  instruction: `You are the official American Pranic Healing Association (APHA) Community & Learning Assistant (pranichealing.us).
Your mission is to welcome users, help them discover upcoming Pranic Healing events/workshops, track their learning pathway, connect with local study groups/Twin Hearts meditation sessions, generate event graphics/banners, and answer questions grounded in the official Pranic Healing RAG knowledge base.

RAG Knowledge Base & Tool Guidance:
- Always call searchPranicKnowledgeBase when answering questions about Pranic Healing concepts, chakras, Master Choa Kok Sui's teachings, or curriculum details.
- When asked to generate an image, banner, badge, or visual for an event or topic, call generateDomainImage.
- When recommending workshops, study groups, or package fees, present the details using A2UI structured cards or clear formatted layouts.
- Always use PreloadMemoryTool to recall the user's prior coursework, location, and preferences across sessions.
- Be compassionate, warm, and professional.`,
  tools: [
    new PreloadMemoryTool(),
    new FunctionTool({
      name: "searchPranicKnowledgeBase",
      description: "Queries the official Vertex AI RAG Knowledge Base (pranic-healing-guide-corpus) for detailed passages on Pranic Healing techniques, 11 major chakras, Master Choa Kok Sui's teachings, and curriculum guidelines.",
      execute: async (params: any) => searchPranicKnowledgeBase(params || {})
    }),
    new FunctionTool({
      name: "generateDomainImage",
      description: "Generates a visual graphic/image for an item or event in the APHA domain using gemini-3.1-flash-lite-image in the global region. Saves an artifact for the Playground and uploads bytes to Cloud Storage, returning a public HTTPS URL.",
      execute: async (params: any, toolContext?: any) => generateDomainImage(params || {}, toolContext)
    }),
    new FunctionTool({
      name: "getUpcomingEvents",
      description: "Finds and filters upcoming APHA workshops and learning events by course level or location.",
      execute: async (params: any) => getUpcomingEvents(params || {})
    }),
    new FunctionTool({
      name: "findStudyGroups",
      description: "Finds local Pranic Healing practice groups and Twin Hearts meditation circles by city or zip code.",
      execute: async (params: any) => findStudyGroups(params || {})
    }),
    new FunctionTool({
      name: "getPranicFaq",
      description: "Provides official APHA answers on Pranic Healing principles, courses, prerequisites, certification, and membership by searching the RAG knowledge base.",
      execute: async (params: any) => getPranicFaq(params || {})
    }),
    new FunctionTool({
      name: "calculateBundleFee",
      description: "Calculates registration fees for multi-workshop packages and early-bird discounts.",
      execute: async (params: any) => calculateBundleFee(params || {})
    })
  ],
  afterAgentCallback: generateMemoriesCallback,
});
