import { GoogleGenAI } from '@google/genai';
import { Storage } from '@google-cloud/storage';

const PROJECT_ID = process.env.GOOGLE_CLOUD_PROJECT || "qwiklabs-gcp-04-a63326fe2771";
const BUCKET_NAME = "apha-agent-public-images-qwiklabs-gcp-04-a63326fe2771";

const storage = new Storage({ projectId: PROJECT_ID });

async function ensurePublicBucket(bucketName: string) {
  const bucket = storage.bucket(bucketName);
  const [exists] = await bucket.exists();
  if (!exists) {
    await storage.createBucket(bucketName, {
      location: 'us-central1',
      storageClass: 'STANDARD',
    });
  }
  return bucket;
}

export async function generateDomainImage(
  params: { prompt: string; itemName?: string },
  toolContext?: any
) {
  const ai = new GoogleGenAI({
    vertexai: true,
    project: PROJECT_ID,
    location: 'global',
  });

  const fullPrompt = `Generate a high quality visual graphic for American Pranic Healing Association (APHA): ${params.prompt || params.itemName || 'Meditation on Twin Hearts lotus banner'}`;

  const response = await ai.models.generateContent({
    model: 'gemini-3.1-flash-lite-image',
    contents: fullPrompt,
  });

  const part = response.candidates?.[0]?.content?.parts?.[0];
  if (!part || !part.inlineData || !part.inlineData.data) {
    throw new Error('No image generated by gemini-3.1-flash-lite-image');
  }

  const mimeType = part.inlineData.mimeType || 'image/png';
  const base64Data = part.inlineData.data;
  const imageBuffer = Buffer.from(base64Data, 'base64');

  const timestamp = Date.now();
  const itemNameSlug = (params.itemName || 'apha-visual')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-');
  const filename = `${itemNameSlug}-${timestamp}.${mimeType.includes('jpeg') || mimeType.includes('jpg') ? 'jpg' : 'png'}`;

  // (1) Save artifact for Playground Artifacts panel
  if (toolContext && typeof toolContext.saveArtifact === 'function') {
    await toolContext.saveArtifact(filename, {
      inlineData: {
        mimeType,
        data: base64Data,
      },
    });
    console.log(`Saved artifact "${filename}" to toolContext.`);
  }

  // (2) Upload bytes directly to Cloud Storage bucket and return public HTTPS URL
  const bucket = await ensurePublicBucket(BUCKET_NAME);
  const file = bucket.file(filename);

  await file.save(imageBuffer, {
    metadata: { contentType: mimeType },
    public: true,
    resumable: false,
  });

  try {
    await file.makePublic();
  } catch (e) {
    // Ignore error if uniform bucket-level access is enabled
  }

  const publicUrl = `https://storage.googleapis.com/${BUCKET_NAME}/${filename}`;

  return {
    success: true,
    filename,
    mimeType,
    publicUrl,
    a2uiSurface: {
      type: "Card",
      header: `APHA Visual: ${params.itemName || 'Pranic Healing Graphic'}`,
      fields: [
        { label: "Public Storage URL", value: publicUrl },
        { label: "Mime Type", value: mimeType }
      ],
      image: { url: publicUrl }
    }
  };
}

async function testRun() {
  console.log('Testing generateDomainImage tool...');
  const mockCtx = {
    saveArtifact: async (fn: string, art: any) => {
      console.log(`[Mock toolContext] saveArtifact called with filename: ${fn}`);
    }
  };

  const result = await generateDomainImage(
    { prompt: 'Glowing golden heart chakra lotus for Pranic Healing event banner', itemName: 'Twin Hearts Lotus' },
    mockCtx
  );

  console.log('Tool Execution Result:', JSON.stringify(result, null, 2));
}

if (require.main === module) {
  testRun().catch(err => {
    console.error('Test Error:', err);
  });
}
